# Generated by Django 5.2.1 on 2025-05-15 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='child',
            name='education_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='joined_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
