# Generated by Django 5.2.1 on 2025-05-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_address_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('teacher', 'Teacher'), ('sponsor', 'Sponsor')], default='staff', max_length=10),
        ),
    ]
